DET_SOURCE_DIR: '/mnt/c/Users/83725/Desktop/AIC21-MTMC/datasets/detection/images/test/S06/'
REID_MODEL: '/mnt/c/Users/83725/Desktop/AIC21-MTMC/detector/yolov5/reid/reid_model/resnet101_ibn_a_2.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/mnt/c/Users/83725/Desktop/AIC21-MTMC/datasets/detect_merge/'
DATA_DIR: '/mnt/c/Users/83725/Desktop/AIC21-MTMC/datasets/detect_reid1/'
REID_SIZE_TEST: [384, 384]

